feat: support batched add requests in `RequestQueue `
apify/apify-ts pull request #60
Opened 2022-03-16 15:41 UTC by vladfrangu

I've only done preliminary tests, however it's mostly a copy-paste of addRequest with added handling for multiple requests

Closes https://github.com/apify/apify-ts/issues/58

2022-03-16 15:46 UTC, vladfrangu commented
Ah, Actions have some issues... That explains why CI is not running rn
![image](https://user-images.githubusercontent.com/17960496/158630602-1acf0c44-3a37-404b-a1ad-afc51aa50ea9.png)

2022-03-22 10:09 UTC, B4nan requested changes
i would like to see some integration tests, seems like you only tested the client method is called, but not that it actually works

@valekjo could you please take a peek at this? also how does the `unprocessedRequests` work, do we need to handle that somehow here? do you think we should make this opt in and fallback to something like `Promise.add(reqs.map(req => rq.addRequest(req))` (in batches)? this is v3, so it wont be stable at least for a month or two, and we will be doing quite a lot of testing before it gets stable, so we will catch issues early during internal testing in case it would be broken on api end

2022-03-23 14:23 UTC, vladfrangu commented
> i would like to see some integration tests, seems like you only tested the client method is called, but not that it actually works

I'd love to setup an E2E test for this, maybe I can get some help from @AndreyBykov with doing it if he has time? Would also let us see if the endpoint works

2022-03-23 14:34 UTC, B4nan commented
Mmmm actually, I am quite sure it will not work, as those tests work locally, and we don't have the batch support implemented in storage-local! Please take a look at that too, do it in the https://github.com/apify/apify-storage-local-js repo, not in the monorepo copy, so we can publish it.

2022-03-27 18:54 UTC, vladfrangu commented
> also how does the `unprocessedRequests` work, do we need to handle that somehow here?

At a first glance, it seems to return requests that weren't added to the request queue (at a glance it seems to be requests that already exist in the queue that would be filled in here). I don't think we want to re-add them again forcefully

2022-04-04 15:38 UTC, B4nan commented on test/storage-local/request_queues.test.ts
> +test.only('addRequests', async () => {
```suggestion
test('addRequests', async () => {
```

2022-04-04 15:40 UTC, vladfrangu commented on test/storage-local/request_queues.test.ts
> +test.only('addRequests', async () => {
Woops, thx

2022-04-05 15:15 UTC, merged