chore: backport apify-js commits
apify/apify-ts pull request #61
Opened 2022-03-17 22:13 UTC by barjin

2022-03-19 10:13 UTC, B4nan requested changes
few nitpicks

2022-03-19 10:13 UTC, B4nan commented on test/apify/crawlers/puppeteer_crawler.test.ts
> +    let proxyConfiguration : ProxyConfiguration;
how come this is not caught by eslint

```suggestion
    let serverUrl: string;
    let proxyConfiguration: ProxyConfiguration;
```

2022-03-21 13:05 UTC, barjin commented on packages/utils/src/internals/social.ts
> + * if (Apify.utils.social.DISCORD_REGEX.test('https://www.tiktok.com/@user')) {
Good catch, a copy-paste artifact. The excerpt shown here (from `apify-js`) is btw also flawed, mixing `DISCORD_REGEX` with tiktok URL :) Resolved.

2022-03-21 15:51 UTC, B4nan approved these changes

2022-03-21 15:51 UTC, merged